server:
  servlet:
    context-path: /api
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/events
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  sql:
    init:
      platform: postgresql
      schema-locations: classpath:db/db-schema.sql
      data-locations: classpath:db/initial-data.sql
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
  data:
    web:
      pageable:
        default-page-size: 3

security:
  jwt:
    # validity time in minutes
    validity-time: 30
    secret-key: s1CXLBUbHJ/4rgyxfZZa5dechvLsYaND22sFDMQKyX0HXnpH2WowxUXVPDVKN8fnTUaejQsXQFqjKLPIGm/mN1V4SYfMMoPYZYvPg2sVjbYcnshdyHRlNOhE3ZdYyCFNk7JQ8qK+yWxeFnK+IAZ86p8M2Qec2WvsJEnc2ivBKHDMjNZs0sCvAhBFSVi4Q/OQXJbX1Zo3TioKdaNr8tLEJ/iVuRjHx9V8YUwY7HsfjQkbu7ZMvRMk+VHmiL/XcsEEo3GMeR6MGvjp1OiYqvXvRJBdUUQOIwpBao2tc2AIfsj3udi8g69J3D9qMMb3Kc4+3CtDTPeRCSIt87AjXUzCaU6Ul3kfRcHO7PoPDOEDllkzbxrTzC+O5axSevsS3P6wAvYRGJ85Wl4iHfCOHUCNAutxLp7qNDrIDHVsahl2KJkHbrrtwXimeGc/XGAspWA4mLg7J+7RkWjiAb2QZLb0eJ8Gpe9pI1hJ3YsK3bgGN5IJUW0fPN2xeYCPE+/mbsj3DEvl/CKK61Q6yG9MGunfOtUv8nQeh5lQfytAQGr6szMub3r+jaQUa4RgJZ8wSa+blooKlaycShsR5AqZ5ZLQq8btf94UCe9grHFp7wtAmFc0eX7QPJH6TizJUZvti3vhnywvxNvYxO7A/kjNsqhRJiKkbp3ZMnlraQBS4QgS16A=