spring:
  main:
    banner-mode: console
  datasource:
    url: jdbc:h2:mem:default
    driver-class-name: org.h2.Driver
    username: events
    password: events
  #  sql:
  #    init:
  #      schema-locations:
  #      classpath:db/db-user.sql
  #      classpath:db/db-event.sql
  #      data-locations:
  #      classpath:db/initial-data.sql
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
